### ISSUE TITLE
Fix non-tiling textures

### ISSUE THREAD

**Issue by gajop** [gajop/Scenario-Editor-Resources#3]
Some textures don't tile:
https://github.com/gajop/Scenario-Editor-Resources/blob/master/brush_textures/grass/grass-tall.jpg
https://github.com/gajop/Scenario-Editor-Resources/blob/master/brush_textures/man-made/concrete2.jpg
https://github.com/gajop/Scenario-Editor-Resources/blob/master/brush_textures/Other%20groundcover/clovers.png

**Comment by aeonios** [comment]
Fixed.
