### ISSUE TITLE
Installing documentation

### ISSUE THREAD

**Issue by sanguinariojoe** [gajop/Scenario-Editor-Resources#4]
Where should it be placed?

**Comment by gajop** [comment]
Oh. This repo is outdated. I suppose I should delete it. 

See https://github.com/Spring-SpringBoard/SpringBoard-Core#assets for how to download assets. I'm moving the more detailed docs to readthedocs http://springboard-core.readthedocs.io/en/latest/ They are to be written here: https://github.com/Spring-SpringBoard/SpringBoard-Core/tree/master/doc

It's unfortunate but Git is a bad choice for large files. 

PS: I think I may need to update those assets that are linked. I made some local changes but I haven't uploaded it yet :/

**Comment by gajop** [comment]
I've now updated the assets on google drive. Follow SB's main documentation.
This repository will be removed soon.
